import { MemoryItem, Session, AgentWorkflow } from './types';

export const INITIAL_SESSIONS: Session[] = [
  {
    id: 'session-1',
    title: 'Profile & Background Setup',
    description: 'Initial interaction: Stored user identity, role, and overarching objectives.',
    createdAt: 'Sep 23, 14:20',
    messageCount: 4,
  },
  {
    id: 'session-2',
    title: 'Architecture & Tech Stack Decisions',
    description: 'Framework selection: React 19, TypeScript, Mem0, OpenMemory MCP, LangChain.',
    createdAt: 'Sep 24, 09:15',
    messageCount: 6,
  },
  {
    id: 'session-3',
    title: 'Sprint Planning & Constraints',
    description: 'Active session: Building multi-agent memory workflows without starting from scratch.',
    createdAt: 'Today, 11:30',
    messageCount: 3,
  },
];

export const INITIAL_MEMORIES: MemoryItem[] = [
  {
    id: 'mem-1',
    content: 'User is Htoo Aung Lin, Senior AI Engineer building production-grade autonomous assistants.',
    category: 'identity',
    confidence: 0.99,
    timestamp: 'Sep 23, 14:22',
    sessionId: 'session-1',
    sessionTitle: 'Profile & Background Setup',
    pinned: true,
    accessCount: 14,
    lastRecalledAt: 'Just now',
    sentiment: 'positive',
    tags: ['Profile', 'AI Engineer', 'Autonomous Agents'],
  },
  {
    id: 'mem-2',
    content: 'Preferred Tech Stack: React 19, TypeScript, Tailwind CSS, Mem0, OpenMemory MCP, LangChain, and CrewAI.',
    category: 'preference',
    confidence: 0.98,
    timestamp: 'Sep 24, 09:18',
    sessionId: 'session-2',
    sessionTitle: 'Architecture & Tech Stack Decisions',
    pinned: true,
    accessCount: 11,
    lastRecalledAt: 'Just now',
    sentiment: 'positive',
    tags: ['React 19', 'TypeScript', 'Tailwind', 'Mem0', 'LangChain'],
  },
  {
    id: 'mem-3',
    content: 'System Constraint: Never wipe context across sessions; always query persistent vector memory before answering.',
    category: 'constraint',
    confidence: 0.97,
    timestamp: 'Sep 24, 09:25',
    sessionId: 'session-2',
    sessionTitle: 'Architecture & Tech Stack Decisions',
    pinned: true,
    accessCount: 9,
    lastRecalledAt: '5m ago',
    sentiment: 'negative',
    tags: ['Persistence', 'Vector Memory', 'No Wipe', 'Rules'],
  },
  {
    id: 'mem-4',
    content: 'Multi-Agent Workflow: CrewAI agents coordinate with Mem0 vector store to retrieve cross-session context before answering complex tasks.',
    category: 'workflow',
    confidence: 0.96,
    timestamp: 'Sep 24, 09:40',
    sessionId: 'session-2',
    sessionTitle: 'Architecture & Tech Stack Decisions',
    accessCount: 6,
    lastRecalledAt: '12m ago',
    sentiment: 'neutral',
    tags: ['CrewAI', 'Orchestration', 'Agent Swarm'],
  },
  {
    id: 'mem-5',
    content: 'Project Vision: An AI assistant that remembers useful context across different conversations instead of starting from zero every time.',
    category: 'project',
    confidence: 0.99,
    timestamp: 'Sep 23, 14:24',
    sessionId: 'session-1',
    sessionTitle: 'Profile & Background Setup',
    pinned: true,
    accessCount: 16,
    lastRecalledAt: 'Just now',
    sentiment: 'positive',
    tags: ['Cross-Session', 'Long-Term Memory', 'Vision'],
  },
  {
    id: 'mem-6',
    content: 'Deployment Target: Google Cloud Run containerized service with streaming server-side LLM proxy.',
    category: 'knowledge',
    confidence: 0.92,
    timestamp: 'Sep 24, 10:05',
    sessionId: 'session-2',
    sessionTitle: 'Architecture & Tech Stack Decisions',
    accessCount: 4,
    lastRecalledAt: '1h ago',
    sentiment: 'neutral',
    tags: ['Google Cloud Run', 'Deployment', 'Streaming'],
  },
];

export const INITIAL_AGENTS: AgentWorkflow[] = [
  {
    id: 'agent-1',
    name: 'Mem0 Ingest Agent',
    role: 'Memory Ingestion & Vectorizer',
    tech: 'Mem0 Protocol',
    status: 'completed',
    description: 'Listens to conversations, extracts factual propositions, and calculates confidence embeddings.',
    task: 'Index user preferences & session state into persistent long-term storage.',
    lastRun: '1m ago',
  },
  {
    id: 'agent-2',
    name: 'OpenMemory MCP Agent',
    role: 'Model Context Protocol Bridge',
    tech: 'OpenMemory MCP',
    status: 'running',
    description: 'Bridges cross-session memory nodes to LLM system instructions via standard MCP tools.',
    task: 'Supply real-time recalled context snippets to active prompt context window.',
    lastRun: 'Active',
  },
  {
    id: 'agent-3',
    name: 'CrewAI Synthesis Agent',
    role: 'Contextual Multi-Agent Weaver',
    tech: 'CrewAI + LangChain',
    status: 'idle',
    description: 'Combines multi-session memories with active conversation goals to generate personalized replies.',
    task: 'Harmonize past constraints and current user intents without starting from zero.',
    lastRun: '10m ago',
  },
];

export const INITIAL_CHAT_HISTORIES: Record<string, any[]> = {
  'session-1': [
    {
      id: 'msg-s1-1',
      role: 'user',
      content: "Hello! My name is Htoo Aung Lin. I am working on an AI Assistant with long-term memory so we never start from zero.",
      timestamp: 'Sep 23, 14:21',
    },
    {
      id: 'msg-s1-2',
      role: 'assistant',
      content: "Nice to meet you, Htoo Aung Lin! I've initialized our persistent Mem0 vector graph and committed your identity and core objective. As we collaborate across days and different sessions, this knowledge will stay permanently attached to your profile.",
      timestamp: 'Sep 23, 14:22',
      recalledMemories: [
        "User is Htoo Aung Lin",
        "Project: AI Assistant with long-term memory",
      ],
    },
    {
      id: 'msg-s1-3',
      role: 'user',
      content: "Awesome. Make sure this memory persists even if I refresh or open a new conversation thread.",
      timestamp: 'Sep 23, 14:23',
    },
    {
      id: 'msg-s1-4',
      role: 'assistant',
      content: "Guaranteed. With our OpenMemory MCP integration and local persistent storage, every new session automatically loads past context at boot time.",
      timestamp: 'Sep 23, 14:24',
      recalledMemories: [
        "System Constraint: Never wipe context across sessions",
      ],
    },
  ],
  'session-2': [
    {
      id: 'msg-s2-1',
      role: 'user',
      content: "Let's decide on the tech stack. We'll use React 19, TypeScript, Tailwind CSS, Mem0, OpenMemory MCP, LangChain, and CrewAI.",
      timestamp: 'Sep 24, 09:16',
    },
    {
      id: 'msg-s2-2',
      role: 'assistant',
      content: "I have recorded your tech stack specifications into the persistent memory store. Notice that I still remember your name is Htoo Aung Lin from yesterday's session! What architectural pattern should we establish for multi-agent workflows?",
      timestamp: 'Sep 24, 09:18',
      recalledMemories: [
        "User is Htoo Aung Lin, Senior AI Engineer",
        "Preferred Tech Stack: React 19, TypeScript, Tailwind CSS, Mem0, OpenMemory MCP",
      ],
    },
    {
      id: 'msg-s2-3',
      role: 'user',
      content: "CrewAI will handle multi-agent orchestration, and LangChain will provide tool integration with the OpenMemory MCP server.",
      timestamp: 'Sep 24, 09:20',
    },
    {
      id: 'msg-s2-4',
      role: 'assistant',
      content: "Recorded: CrewAI for orchestration and LangChain for MCP tool integration. This ensures that any specialized agent in the workflow can query our centralized Mem0 graph.",
      timestamp: 'Sep 24, 09:21',
      recalledMemories: [
        "Multi-Agent Workflow: CrewAI agents coordinate with Mem0 vector store",
      ],
    },
  ],
  'session-3': [
    {
      id: 'msg-s3-1',
      role: 'assistant',
      content: "Welcome back, Htoo Aung Lin! 👋\n\nI have loaded your context across Sessions 1 and 2:\n• **Identity**: Htoo Aung Lin (Senior AI Engineer)\n• **Tech Stack**: React 19, TypeScript, Tailwind, Mem0, OpenMemory MCP, LangChain, CrewAI\n• **Core Goal**: AI Assistant that remembers useful context across different conversations instead of starting from zero every time.\n\nWhat are we building in this session?",
      timestamp: 'Today, 11:30',
      recalledMemories: [
        "User is Htoo Aung Lin, Senior AI Engineer building production-grade autonomous assistants.",
        "Preferred Tech Stack: React 19, TypeScript, Tailwind CSS, Mem0, OpenMemory MCP, LangChain, and CrewAI.",
        "Project Vision: An AI assistant that remembers useful context across different conversations instead of starting from zero every time.",
      ],
    },
  ],
};
